pub mod config;
pub mod docker;
pub mod project;

pub use config::*;
pub use project::*;

pub const CHAIN_LIST: [&str; 55] = [
    "amoy",
    "arbitrum-nova",
    "arbitrum-one",
    "arbitrum-sepolia",
    "aurora",
    "avalanche",
    "b2-testnet",
    "base",
    "base-sepolia",
    "blast",
    "blast-sepolia",
    "boba",
    "bsc",
    "bsc-testnet",
    "celo",
    "citrea-testnet",
    "crab",
    "ethereum-mainnet",
    "fantom",
    "flare",
    "fuji",
    "galadriel-devnet",
    "gnosis",
    "gnosis-chiado",
    "goerli",
    "harmony",
    "holesky",
    "kroma",
    "linea",
    "lisk",
    "lukso",
    "lukso-testnet",
    "manta",
    "mantle",
    "metis",
    "mode",
    "moonbase-alpha",
    "moonbeam",
    "morph",
    "morph-testnet",
    "neon-evm",
    "opbnb",
    "optimism",
    "optimism-sepolia",
    "polygon",
    "polygon-zkevm",
    "rsk",
    "saakuru",
    "scroll",
    "sepolia",
    "shimmer-evm",
    "tangle",
    "unichain-sepolia",
    "zeta",
    "zora",
];
